---
- name: Install nsd
  ansible.builtin.apt:
    name: "{{ nsd_package }}"
    state: present

- name: Enable nsd
  ansible.builtin.service:
    name: "{{ nsd_service }}"
    enabled: yes

- name: Create zones directory
  ansible.builtin.file:
    path: "{{ __nsd_zones_dir }}"
    state: directory
    owner: root
    group: "{{ nsd_group }}"

- name: Create master directory
  ansible.builtin.file:
    path: "{{ __nsd_zones_dir }}/master"
    state: directory
    owner: root
    group: "{{ nsd_group }}"
    mode: 0755

- name: Create slave directory
  ansible.builtin.file:
    path: "{{ __nsd_zones_dir }}/slave"
    state: directory
    owner: root
    group: "{{ nsd_group }}"
    mode: 0775
