---
- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Create nsd.conf
  ansible.builtin.template:
    src: nsd.conf.j2
    dest: "{{ nsd_conf_file }}"
    validate: "{{ nsd_bin }} %s"
    mode: 0640
    owner: root
    group: "{{ nsd_group }}"
  notify: Restart nsd

- name: Define today's timestamp
  ansible.builtin.set_fact:
    today: "{{ ansible_date_time.year + ansible_date_time.month + ansible_date_time.day }}"

- ansible.builtin.include_tasks: zonefile.yml
  loop: "{{ nsd_zones }}"
  loop_control:
    loop_var: zone
  when: nsd_role != 'slave'

- name: Ensure nsd is started
  ansible.builtin.service:
    name: "{{ nsd_service }}"
    state: started

- ansible.builtin.meta: flush_handlers
